name: Official build - Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-win:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build with MSVC
      shell: cmd
      env:
        DCUE_APP_KEY: ${{ secrets.DCUE_APP_KEY }}
        DCUE_APP_SECRET: ${{ secrets.DCUE_APP_SECRET }}
        DCUE_APP_XORKEY: ${{ secrets.DCUE_APP_XORKEY }}
      run: .github/win_build.bat

    - uses: actions/upload-artifact@v2
      with:
        name: DCue for Windows
        path: build\dcue.7z
      name: upload-dcue-build
