name: Build and test (Linux)

on: [push, pull_request]

jobs:
  test-lnx:
  
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        compiler: [g++, g++-10, clang++, clang++-12]
        buildtype: [Debug, Release]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install curl
      run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev ninja-build

    - name: Build and test
      env:
        CXX: ${{ matrix.compiler }}
      run: .github/lnx_build_and_test.sh ${{ matrix.buildtype }}
